# Generated by Django 2.1 on 2018-09-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_Nombre', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=500)),
                ('fotejes', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Extreno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_Nombree', models.CharField(max_length=110)),
                ('ext_Idioma', models.CharField(max_length=26)),
                ('ext_descripcion', models.CharField(max_length=500)),
                ('fecha_estreno', models.DateField()),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_genero', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=30)),
                ('fil_Fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('idioma', models.CharField(max_length=40)),
                ('calidad', models.CharField(max_length=40)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('descargas', models.ManyToManyField(blank=True, null=True, to='pelis.Descarga')),
                ('extrenos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelis.Extreno')),
                ('filtros', models.ManyToManyField(blank=True, null=True, to='pelis.Filtro')),
                ('generos', models.ManyToManyField(blank=True, null=True, to='pelis.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_Nombre', models.CharField(max_length=500)),
                ('rec_idioma', models.CharField(max_length=30)),
                ('rec_calidad', models.CharField(max_length=30)),
                ('imga', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('peliculas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelis.Pelicula')),
            ],
        ),
    ]
