# Generated by Django 2.1 on 2018-09-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='extrenos',
        ),
    ]
