# Generated by Django 2.1 on 2018-09-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0002_remove_pelicula_extrenos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacion',
            name='peliculas',
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='mensaje',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
