# Generated by Django 2.1 on 2018-09-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0004_auto_20180913_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='trailer',
        ),
    ]
