# Generated by Django 2.1 on 2018-09-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0005_remove_pelicula_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='Ver_online',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
